### ISSUE TITLE
"Payment Error" Order Status

### ISSUE THREAD

**Issue by ramb0t** [Payfast/mod-prestashop_1_7#3]
Occasionally (especially during high server load) when an order is paid via Payfast, the amount paid is incorrect and prestashop sets the order status as "Payment Error: 

![image](https://user-images.githubusercontent.com/2318303/69502957-7931da80-0f1d-11ea-9628-d130f100cf25.png)

I'm pretty sure this is an issue with the Payfast module, however, I'm unable to recreate the issue in testing, not quite sure how to track down the source of the bug

**Comment by RheinhardtSnyman** [comment]
Hi @robthepyro ,
This module is unfortunately for outdated versions of PrestaShop. PayFast will continue to support security updates for this module but will no longer fix bugs like this.

Please consider updating to Prestashop 1.7 which has been supported by PayFast since 2016.
https://github.com/PayFast/mod-prestashop_1_7
